package bot.wuliang.parser.enums

enum class Tag(val value: String) {
    PRIME("Prime"),
    VAULTED("Vaulted"),
    CORPUS("Corpus"),
    ARBITERS_OF_HEXIS("Arbiters of Hexis"),
    BARO("Baro"),
    CEPHALON("Cephalon"),
    CEPHALON_SIMARIS("Cephalon Simaris"),
    CEPHALON_SUDA("Cephalon Suda"),
    DAGATH("Dagath"),
    DAX("Dax"),
    DUVIRI("Duviri"),
    ENTRATI("Entrati"),
    FOUNDER("Founder"),
    GRINEER("Grineer"),
    INCARNON("Incarnon"),
    INFESTED("Infested"),
    INVASION_REWARD("Invasion Reward"),
    KUVA_LICH("Kuva Lich"),
    LUA("Lua"),
    NEVER_VAULTED("Never Vaulted"),
    NEW_LOKA("New Loka"),
    OROKIN("Orokin"),
    PERRIN_SEQUENCE("Perrin Sequence"),
    THE_PERRIN_SEQUENCE("The Perrin Sequence"),
    PRISMA("Prisma"),
    RED_VEIL("Red Veil"),
    SCALDRA("Scaldra"),
    SENTIENT("Sentient"),
    STALKER("Stalker"),
    STEEL_MERIDIAN("Steel Meridian"),
    SYNDICATE("Syndicate"),
    TECHNOCYTE_CODA("Technocyte Coda"),
    TENET("Tenet"),
    TENNO("Tenno"),
    TUTORIAL("Tutorial"),
    VORUNA("Voruna"),
    VANDAL("Vandal"),
    WRAITH("Wraith"),
    ZARIMAN("Zariman")
}
